FROM bitnami/apache:2.4.62

USER root

RUN mkdir -p /var/lib/apt/lists/partial && \
    apt-get update && \
    apt-get install -y gettext && \
    rm -rf /var/lib/apt/lists/*

USER 1001

ARG DOMAIN

COPY /vhost.conf /vhost.conf

RUN envsubst '${DOMAIN}' < /vhost.conf > /opt/bitnami/apache/conf/vhosts/000-default.conf

RUN echo "Include /opt/bitnami/apache/conf/vhosts/000-default.conf" >> /opt/bitnami/apache/conf/bitnami/bitnami-apps-vhosts.conf
