services:
  init-certs:
    image: alpine
    volumes:
      - type: bind
        source: ./certs
        target: /certs
    command: >
      /bin/sh -c "
      echo 'Starting certificate generation...';
      if [ ! -f /certs/server.crt ] || [ ! -f /certs/server.key ]; then
        echo 'Certificates not found, generating...';
        apk add --no-cache openssl &&
        openssl req -x509 -newkey rsa:4096 -sha256 -days 365 -nodes -keyout /certs/server.key -out /certs/server.crt -subj '/CN=boston.local' &&
        echo 'Certificates generated successfully.';
      else
        echo 'Certificates already exist.';
      fi;
      "
  # MariaDB Service
  db:
    image: mariadb:11.7.2
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always

  # WordPress with PHP-FPM Service
  wordpress:
    image: wordpress:php8.3-fpm
    depends_on:
      - db
      - elasticsearch
      - redis
    user: "www-data"
    build: 
      context: .
      dockerfile: Dockerfile.wordpress
    expose: 
      - "9000"
    volumes:
      - ./wordpress:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
    restart: always

  # Apache Service
  apache:
    image: bitnami/apache:2.4.62
    depends_on:
      - wordpress
      - init-certs
    build: 
      context: .
      dockerfile: Dockerfile.apache
    env_file:
      - local.env
    volumes:
      - ./wordpress:/var/www/html
      - ./certs:/certs  # Mount the shared volume where certificates are stored
      - ./vhost.conf:/opt/bitnami/apache/conf/vhosts/wordpress.conf
    ports:
      - "8444:8443"
    restart: always

  # ElasticSearch Service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - discovery.type=single-node
      - network.bind_host=0.0.0.0
      - network.publish_host=elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - cluster.name=docker-cluster
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  # Redis Service
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --stop-writes-on-bgsave-error no
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_MAXMEMORY=256mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always
  
  # PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    platform: linux/amd64
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
    restart: always

volumes:
  db_data:
  es_data:
  redis_data:
